<template>
    <Head title="Users" />

    <AuthenticatedLayout>
        <template #header> Employees </template>
        <EmployeesTable :employees="dummyEmployeeData"></EmployeesTable>
    </AuthenticatedLayout>
</template>

<script setup>
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import EmployeesTable from "@/Pages/Employees/Index/Components/EmpoyeesTable.vue";
import { Head } from "@inertiajs/vue3";

const dummyEmployeeData = [
    {
        name: "John Doe",
        code: "JD001",
        phone: "123-456-7890",
        department: "IT",
        city: "New York",
        team: "Dev Team",
        status: "Active",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
    {
        name: "Jane Smith",
        code: "JS002",
        phone: "987-654-3210",
        department: "HR",
        city: "San Francisco",
        team: "HR Team",
        status: "Inactive",
    },
];
</script>
